export const theme = {
  colors: {
    blue: "#2F80ED",
    darkGray: "#4F4F4F",
    lightGray: "#828282",
    softGray: "#E0E0E0",
    gray: "#F2F2F2",
    orange: "#F8B76B",
    purple: "#8785FF",
    red: "#EB5757",
    yellow: "#F2C94C",
    baseYellow: "#FCEED3",
    outlineYellow: "#E5A443",
    basePurple: "#EEDCFF",
    outlinePurple: "#9B51E0",
    baseGreen: "#D2F2EA",
    outlineGreen: "#43B78D",
    softBlue: "#E9F3FF",
    softChoco: "#FDCFA4",
    softLightChoco: "#F9E9C3",
    softGreen: "#AFEBDB",
    softLightGreen: "#CBF1C2",
    softPurple: "#CFCEF9",
    softLightPurple: "#F9E0FD",
    customGray: "#F8F8F8",
  },
};
